extends Node

enum EnumCharName {
	ALDRIC, THORINDEL, SERAPHEL, MALACHAR, ELOWEN,
	DRAVETH, LYRANOR, VAELTHAS, KORGRIM, ISOLDE,
	ZEPHYRAN, BRYNDOR, CAELITH, MORDECAI, SYLVARA,
	DRAVENTUS, AELINDRA, THORGASH, VELUNOR, KAELTHAS,
	SERYNDEL, BORGRIM, ELARION, MORTHIS, ZAREVYN,
	ALDRANOR, THYRANDEL, SOLIVETH, KARADUN, ELARYS,
	VAELINDRA, DORGASH, MIRAWEN, THOLVYN, SERAPHIS,
	KALDRATH, ELYNDRA, MORTHAEL, ZARINDEL, BOLVETH,
	CARANDIS, THYLORIN, VORINDEL, ELARINDRA, SOLGRATH,
	MORDYNVEL, ZARVINDEL, ALDORATH, THYRANDIS, ELVORYN, TOTOLINO,
	BROCOLINO, BROCOLINA, PISTACHIO, TOTO, PICOTA, POUIPOUIC, GUNTER,
	GERTTRUDE, MOMOLINO
}

func generate_hero_name() -> String:
	var name_keys: Array = EnumCharName.keys()   
	return name_keys[randi() % name_keys.size()]

func generate_hero_class() -> int:
	var class_keys: Array = CharStats.EnumCharClass.keys()
	return randi() % class_keys.size()
